title: J. Lucas McKay, Ph.D., M.S.C.R.

owner:
  name: J. Lucas McKay
  avatar: bio-photo.jpg
  email: lucas@dbmi.emory.edu
  twitter: jlucasmckay
  linkedin: jlucasmckay
  github: jlucasmckay
  orcid: 0000-0002-8361-8943
  
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-minimal
